baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Jack's Portfolio"
theme = "basic"
[params]
    author = "Jack Hughes"
    description = "Jack's Portfolio Site"
    gh_url = "https://api.github.com/users"
    gh_user = "ryanrix"